import './JS/header';
import './JS/openModalOrderTour';
import './JS/closeModalOrderTour';
import './JS/formOrderTour';
import './JS/toggleTours';
import './JS/sliderTours';
import './JS/advantages';
//import './JS/reviewsData';
import './JS/reviews';